apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/opsguideme/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook